### ISSUE TITLE
Plugin does not install on Kodi 17.1 MacOS

### ISSUE THREAD

**Issue by kumarpranay** [blxd/plugin.video.livestreamer#1]
The plugin does not install on Kodi 17.1 running on MacOS. To be accurate it shows the "Addon Installed" but then shows a error popup. Kodi logs indicate the address is already in use error on services.py sript.

**Comment by beardypig** [comment]
@blxd is no longer maintaining this addon. There is an equivalent addon for `streamlink`, that I maintain: https://github.com/beardypig/plugin.video.streamlink

**Comment by kumarpranay** [comment]
Thanks. I am having trouble finding a released addon though. And the repository does not list this plugin.

**Comment by beardypig** [comment]
Did you install the beardypig repo? https://github.com/beardypig/repository.beardypig.plugins

**Comment by kumarpranay** [comment]
Yes I did. Gives me a video plugin "TV Catchup (blxd edition)" but not a generic streamlink player.

**Comment by beardypig** [comment]
Ah, yes. It cannot be installed manually only as a dependency to another addon, as you cannot use it without another addon.

**Comment by kumarpranay** [comment]
thanks. Have been using it for my needs since. Would be nice if you can pull from upstream and the current version 0.6.0 is quite dated.

**Comment by beardypig** [comment]
There is a new version work in progress :)
